// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DiaryEntriesPublic = {
    data: Array<DiaryEntryPublic>;
    count: number;
};

export type DiaryEntryCreate = {
    title: string;
    content: string;
    mood?: (string | null);
    tags?: (string | null);
    /**
     * AI-generated tags
     */
    ai_tags?: (string | null);
    /**
     * AI-detected emotional state
     */
    ai_emotional_state?: (string | null);
    /**
     * AI-assessed severity score (1-10)
     */
    ai_severity_score?: (number | null);
    /**
     * AI-extracted keywords
     */
    ai_keywords?: (string | null);
    /**
     * AI-generated summary and insights
     */
    ai_summary?: (string | null);
    /**
     * When AI analysis was performed
     */
    ai_analysis_timestamp?: (string | null);
};

export type DiaryEntryPublic = {
    title: string;
    content: string;
    mood?: (string | null);
    tags?: (string | null);
    /**
     * AI-generated tags
     */
    ai_tags?: (string | null);
    /**
     * AI-detected emotional state
     */
    ai_emotional_state?: (string | null);
    /**
     * AI-assessed severity score (1-10)
     */
    ai_severity_score?: (number | null);
    /**
     * AI-extracted keywords
     */
    ai_keywords?: (string | null);
    /**
     * AI-generated summary and insights
     */
    ai_summary?: (string | null);
    /**
     * When AI analysis was performed
     */
    ai_analysis_timestamp?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
    owner_id: string;
};

export type DiaryEntryUpdate = {
    title?: (string | null);
    content?: (string | null);
    mood?: (string | null);
    tags?: (string | null);
    ai_tags?: (string | null);
    ai_emotional_state?: (string | null);
    ai_severity_score?: (number | null);
    ai_keywords?: (string | null);
    ai_summary?: (string | null);
    ai_analysis_timestamp?: (string | null);
};

/**
 * Model for creating a new goal
 */
export type GoalCreate = {
    /**
     * Goal title
     */
    title: string;
    /**
     * Goal description
     */
    description?: (string | null);
    /**
     * Goal type (e.g., short-term, long-term, habit, etc.)
     */
    goal_type: string;
    /**
     * Target completion date in ISO format
     */
    target_date?: (string | null);
    /**
     * Target duration in days
     */
    target_duration?: (number | null);
    /**
     * Hours logged towards this goal
     */
    progress_hours?: number;
    /**
     * Days worked on this goal
     */
    progress_days?: number;
};

/**
 * Public goal model returned by the API
 */
export type GoalPublic = {
    /**
     * Goal title
     */
    title: string;
    /**
     * Goal description
     */
    description?: (string | null);
    /**
     * Goal type (e.g., short-term, long-term, habit, etc.)
     */
    goal_type: string;
    /**
     * Target completion date in ISO format
     */
    target_date?: (string | null);
    /**
     * Target duration in days
     */
    target_duration?: (number | null);
    /**
     * Hours logged towards this goal
     */
    progress_hours?: number;
    /**
     * Days worked on this goal
     */
    progress_days?: number;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Response model for multiple goals
 */
export type GoalsPublic = {
    data: Array<GoalPublic>;
    count: number;
};

/**
 * Model for updating an existing goal. All fields are optional.
 */
export type GoalUpdate = {
    /**
     * Goal title
     */
    title?: (string | null);
    /**
     * Goal description
     */
    description?: (string | null);
    /**
     * Goal type
     */
    goal_type?: (string | null);
    /**
     * Target completion date in ISO format
     */
    target_date?: (string | null);
    /**
     * Target duration in days
     */
    target_duration?: (number | null);
    /**
     * Hours logged towards this goal
     */
    progress_hours?: (number | null);
    /**
     * Days worked on this goal
     */
    progress_days?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Public insight model for API responses
 */
export type InsightPublic = {
    /**
     * The insight content
     */
    content: string;
    /**
     * Type of insight: motivational, goal_progress, mental_health, etc.
     */
    insight_type: string;
    /**
     * Priority level 1-5 (5 being highest)
     */
    priority?: number;
    /**
     * Whether user has read this insight
     */
    is_read?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Model for requesting AI insights
 */
export type InsightRequest = {
    /**
     * Type: daily, weekly, goal_focused, mood_analysis
     */
    analysis_type?: string;
    include_goals?: boolean;
    include_diary_mood?: boolean;
    max_insights?: number;
};

/**
 * Response model for multiple insights
 */
export type InsightsPublic = {
    data: Array<InsightPublic>;
    count: number;
};

/**
 * Model for updating insights
 */
export type InsightUpdate = {
    content?: (string | null);
    is_read?: (boolean | null);
    priority?: (number | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DiaryReadDiaryEntriesData = {
    limit?: number;
    /**
     * Filter by mood
     */
    mood?: (string | null);
    /**
     * Search in title and content
     */
    search?: (string | null);
    skip?: number;
    /**
     * Filter by tags (comma-separated)
     */
    tags?: (string | null);
};

export type DiaryReadDiaryEntriesResponse = (DiaryEntriesPublic);

export type DiaryCreateDiaryEntryData = {
    requestBody: DiaryEntryCreate;
};

export type DiaryCreateDiaryEntryResponse = (DiaryEntryPublic);

export type DiaryReadDiaryEntryData = {
    id: string;
};

export type DiaryReadDiaryEntryResponse = (DiaryEntryPublic);

export type DiaryUpdateDiaryEntryData = {
    id: string;
    requestBody: DiaryEntryUpdate;
};

export type DiaryUpdateDiaryEntryResponse = (DiaryEntryPublic);

export type DiaryDeleteDiaryEntryData = {
    id: string;
};

export type DiaryDeleteDiaryEntryResponse = (Message);

export type DiaryGetDiaryStatsResponse = ({
    [key: string]: unknown;
});

export type GoalsReadGoalsData = {
    limit?: number;
    skip?: number;
};

export type GoalsReadGoalsResponse = (GoalsPublic);

export type GoalsCreateGoalEndpointData = {
    requestBody: GoalCreate;
};

export type GoalsCreateGoalEndpointResponse = (GoalPublic);

export type GoalsReadGoalData = {
    id: string;
};

export type GoalsReadGoalResponse = (GoalPublic);

export type GoalsUpdateGoalEndpointData = {
    id: string;
    requestBody: GoalUpdate;
};

export type GoalsUpdateGoalEndpointResponse = (GoalPublic);

export type GoalsDeleteGoalEndpointData = {
    id: string;
};

export type GoalsDeleteGoalEndpointResponse = (Message);

export type GoalsUpdateGoalProgressEndpointData = {
    daysToAdd?: number;
    hoursToAdd?: number;
    id: string;
};

export type GoalsUpdateGoalProgressEndpointResponse = (GoalPublic);

export type InsightsGetUserInsightsData = {
    limit?: number;
    skip?: number;
    unreadOnly?: boolean;
};

export type InsightsGetUserInsightsResponse = (InsightsPublic);

export type InsightsGenerateDailyInsightsData = {
    requestBody?: InsightRequest;
};

export type InsightsGenerateDailyInsightsResponse = (InsightsPublic);

export type InsightsGetInsightData = {
    insightId: string;
};

export type InsightsGetInsightResponse = (InsightPublic);

export type InsightsUpdateInsightEndpointData = {
    insightId: string;
    requestBody: InsightUpdate;
};

export type InsightsUpdateInsightEndpointResponse = (InsightPublic);

export type InsightsMarkInsightReadData = {
    insightId: string;
};

export type InsightsMarkInsightReadResponse = (InsightPublic);

export type InsightsCleanupOldInsightsData = {
    daysOld?: number;
};

export type InsightsCleanupOldInsightsResponse = (Message);

export type InsightsGetDashboardInsightsResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);